import type { GameMeta } from './types.js';

export const GAMES: GameMeta[] = [
  {
    id: 'xiangqi',
    nameZh: '中国象棋',
    nameEn: 'Xiangqi',
    genre: '古典棋类',
    playable: 'full-ai',
    players: '2',
    summary: '楚河汉界，车马炮兵。红黑对坐，把对方将死即可。',
    encyclopedia: `中国象棋双方各十六子：帅/将、仕/士、相/象、车、马、炮、兵/卒。车走直线，马走日忌蹩腿，炮隔子打，兵过河后可左右移动。目标是将死对方将帅。\n本馆提供完整走法、将军提示，以及可以给建议的电脑对手。`,
    tutorial: ['你执红，电脑执黑。', '点自己的棋子，高亮格即可落子。', '被将军时请先应将。', '需要提示时，点「请教练帮忙」。'],
  },
  {
    id: 'aeroplane',
    nameZh: '飞行棋',
    nameEn: 'Aeroplane Chess',
    genre: '竞速桌游',
    playable: 'full-ai',
    players: '2-4',
    summary: '掷骰起飞，路上撞人送回停机坪。先把飞机全部送抵终点的人获胜。',
    encyclopedia: `飞行棋是常见的家庭竞速游戏。掷到 6 通常可以起飞或再掷。走到对手所在格可将其打回。进入终点航道需要正好的步数。\n本馆为四色对局，可与电脑同桌。`,
    tutorial: ['先掷骰，再点可以移动的飞机。', '掷出 6 可起飞。', '叠在对手身上会把它送回机库。', '终点要步数刚好。'],
  },
  {
    id: 'werewolf',
    nameZh: '狼人杀',
    nameEn: 'Werewolf',
    genre: '社交推理',
    playable: 'full-bots',
    players: '6-12',
    summary: '夜里有人倒下，白天一起投票。找出狼人，或让狼人屠尽好人。',
    encyclopedia: `狼人杀分狼人与好人（村民和神职）。夜晚：狼人刀人、预言家查验、女巫用药、猎人可在出局时开枪。白天发言后投票放逐。\n本馆提供机器人局，也可开联机房。身份提示会清楚标出阵营色。`,
    tutorial: ['先看自己的身份。', '夜晚按提示行动。', '白天投票放逐可疑的人。', '猎人出局可以带走一人。'],
  },
  {
    id: 'avalon',
    nameZh: '阿瓦隆',
    nameEn: 'Avalon',
    genre: '阵营对抗',
    playable: 'full-bots',
    players: '5-10',
    summary: '组队出征。好人要任务成功，隐匿的反派会在任务里投失败票。',
    encyclopedia: `阿瓦隆比的是信任。队长提名小队，全员投票；通过后队员暗中决定任务成败。好人完成足够成功任务即胜；刺客仍可能在最后刺杀梅林翻盘。\n本馆有机器人同伴，也可联机。`,
    tutorial: ['先记住自己的阵营。', '队长提名后，大家投票。', '出征队员选择成功或失败。', '若你是刺客，好人获胜后仍可刺杀梅林。'],
  },
  {
    id: 'chess',
    nameZh: '国际象棋',
    nameEn: 'Chess',
    genre: '古典棋类',
    playable: 'full-ai',
    players: '2',
    summary: '白黑六兵种，把对方国王将死。支持易位、过路兵与升变。',
    encyclopedia: `国际象棋在 8×8 棋盘上进行。王、后、车、象、马、兵走法各异。本引擎包含易位、吃过路兵和兵的升变，并配有合法格高亮与建议着法。`,
    tutorial: ['你执白。点棋子看可走格。', '注意易位与升变。', '需要思路时请教练看一眼。'],
  },
  {
    id: 'checkers',
    nameZh: '跳棋',
    nameEn: 'Chinese Checkers',
    genre: '竞速棋类',
    playable: 'full-ai',
    players: '2-6',
    summary: '在星形盘上单步或连跳，先把棋子全部送到对面营地。',
    encyclopedia: `中国跳棋可以走进相邻空点，也可以跳过相邻棋子并连续跳跃。本馆先开放双人对电脑。`,
    tutorial: ['点己方棋子，再点高亮落点。', '能跳就尽量连跳。', '占满对方营地即胜。'],
  },
  {
    id: 'mahjong',
    nameZh: '麻将',
    nameEn: 'Mahjong',
    genre: '牌类',
    playable: 'full-bots',
    players: '4',
    summary: '万饼条与字牌。吃碰杠胡，三家电脑陪打。',
    encyclopedia: `简化麻将：万、饼、条与字牌。以四面子加一对将为和牌。可吃下家、碰杠任意家。番种与花牌可增强。`,
    tutorial: ['轮到你时打牌。', '别人打出的牌可碰或胡。', '下家的牌可吃成顺子。', '听牌后把握自摸或点炮。'],
  },
  {
    id: 'gomoku',
    nameZh: '五子棋',
    nameEn: 'Gomoku',
    genre: '古典棋类',
    playable: 'full-ai',
    players: '2',
    summary: '十五路棋盘，先连成五子的人获胜。',
    encyclopedia: `双方轮流落子，横竖斜连成五子即胜。电脑会优先拦截你的四连。无禁手规则，可增强。`,
    tutorial: ['你执黑先行。', '连五即胜。', '注意自己的冲四，也要挡住对方。'],
  },
  {
    id: 'go',
    nameZh: '围棋',
    nameEn: 'Go',
    genre: '古典棋类',
    playable: 'full-ai',
    players: '2',
    summary: '九路入门：气尽被提，双方停着后比较子数与提子。',
    encyclopedia: `围棋在交叉点落子，没有气的棋会被提掉。本馆先做九路：禁止自杀，有简单劫；终局用子数加提子、白贴 3.5 目。完整劫争、数目与十九路可增强。`,
    tutorial: ['你执黑。空交叉点即可落子。', '围住对方、让其无气即可提子。', '连续两手停着即收官。'],
  },
  {
    id: 'junqi',
    nameZh: '军棋',
    nameEn: 'Jungle Chess',
    genre: '军略棋类',
    playable: 'full-ai',
    players: '2',
    summary: '先以斗兽棋开打：比大小、过河跳河，攻入兽穴获胜。',
    encyclopedia: `完整陆战棋需要暗子与军旗。本馆先提供斗兽棋：象至鼠八兽，狮虎可跳河，鼠可过河并吃象。进入对方兽穴即胜。陆战棋暗子可增强。`,
    tutorial: ['你执红，点棋再点落点。', '陷阱里的棋会被任何棋吃掉。', '把棋走进对方兽穴。'],
  },
  {
    id: 'doudizhu',
    nameZh: '斗地主',
    nameEn: 'Dou Dizhu',
    genre: '牌类',
    playable: 'full-bots',
    players: '3',
    summary: '你当地主，两名农民由电脑担任。先出完手牌者胜。',
    encyclopedia: `简化斗地主：跳过叫分，你拿底牌当地主。支持单张、对子、三带、顺子、炸弹与王炸。完整叫分与飞机可增强。`,
    tutorial: ['选中要出的牌，再点出牌。', '大过上家，或点不要。', '炸弹可以压普通牌型。'],
  },
  {
    id: 'uno',
    nameZh: 'UNO',
    nameEn: 'UNO',
    genre: '牌类',
    playable: 'full-bots',
    players: '2-4',
    summary: '颜色或数字对上就能出。功能牌会让场面一下子热闹起来。',
    encyclopedia: `按颜色或数字出牌。万能牌改色，跳过、反转、+2、+4 均已实现。三名电脑对手。先出完者胜。罚分与挑战+4 可增强。`,
    tutorial: ['对上颜色或数字即可出牌。', '万能牌请选一个颜色。', '没有牌就摸一张。'],
  },
  {
    id: 'holdem',
    nameZh: '德州扑克',
    nameEn: "Texas Hold'em",
    genre: '牌类',
    playable: 'full-bots',
    players: '2-9',
    summary: '两人限注练习桌：跟注或加注后发齐公共牌摊牌。',
    encyclopedia: `标准德州是底牌两张、公共牌五张。本馆先做双人练习：跟注后一次发齐五张再比牌。分街下注、边池与多人可增强。`,
    tutorial: ['先看自己的两张底牌。', '选择跟注、加注或弃牌。', '摊牌时五张公共牌大家共用。'],
  },
  {
    id: 'monopoly',
    nameZh: '大富翁',
    nameEn: 'Monopoly-like',
    genre: '经济桌游',
    playable: 'full-bots',
    players: '2-6',
    summary: '掷骰走环线，买地收租，直到只剩一位还有现金。',
    encyclopedia: `简化经济环线：起点发薪、地产买卖与租金、税格。房屋、完整机会卡与拍卖可增强。`,
    tutorial: ['掷骰前进。', '空地可以买下。', '停在别人的地要付租金。', '钱花光即破产。'],
  },
];

export function getGame(id: string) {
  return GAMES.find((g) => g.id === id);
}
