import type { GameMeta } from './types.js';

export const GAMES: GameMeta[] = [
  {
    id: 'xiangqi',
    nameZh: '中国象棋',
    nameEn: 'Xiangqi',
    genre: '古典棋类',
    playable: 'full-ai',
    players: '2',
    summary: '楚河汉界之上，车马炮兵星轨交汇。红黑对弈，智慧与胆识的深空决斗。',
    encyclopedia: `中国象棋是中华文明的战略瑰宝。棋盘以「楚河汉界」为界，红黑各十六子：帅/将、仕/士、相/象、车、马、炮、兵/卒。
目标是将死对方将帅。车直线纵横；马走日忌蹩腿；炮需隔子打；兵过河威力倍增。
星域棋庭提供完整规则引擎、合法着法高亮与启发式 AI 教练，适合入门到进阶的星际对弈者。`,
    tutorial: ['选择红方或黑方对战 AI', '点击己方棋子查看合法落点（霓虹高亮）', '吃子、将军、应将均有提示', 'AI 教练可给出启发式建议着法'],
  },
  {
    id: 'aeroplane',
    nameZh: '飞行棋',
    nameEn: 'Aeroplane Chess',
    genre: '竞速桌游',
    playable: 'full-ai',
    players: '2-4',
    summary: '四色战机从空港启航，骰点驱动跃迁，碰撞即返航，先全员抵达终点者胜。',
    encyclopedia: `飞行棋（Aeroplane Chess）是风靡华人世界的家庭竞速游戏。玩家轮流掷骰，将飞机从停机坪起飞（通常需掷出 6），沿航道前进，可撞击对手使其返航，叠机可加速。全部飞机进入终点跑道即获胜。
本站实现本地 vs AI，支持完整起飞、撞击、叠机与终点规则。`,
    tutorial: ['掷骰决定移动步数', '掷出 6 可起飞或再掷', '落在对手棋子上可击落返航', '进入终点航道需精确步数'],
  },
  {
    id: 'werewolf',
    nameZh: '狼人杀',
    nameEn: 'Werewolf',
    genre: '社交推理',
    playable: 'full-bots',
    players: '6-12',
    summary: '夜幕降临星港，狼人潜行猎杀；预言家查验、女巫用药、猎人带走——白天投票放逐。',
    encyclopedia: `狼人杀是经典社交推理游戏。阵营分为狼人与好人（村民及神职）。夜间：狼人刀人、预言家查验、女巫毒/救、猎人可开枪。白天：发言后投票放逐。
本站实现狼/预言家/女巫/猎人/村民完整闭环，支持机器人局与在线房间。`,
    tutorial: ['夜晚按神职顺序行动', '白天讨论并投票放逐', '猎人被刀/放逐可开枪', '屠边或屠城判定胜负'],
  },
  {
    id: 'avalon',
    nameZh: '阿瓦隆',
    nameEn: 'Avalon',
    genre: '阵营对抗',
    playable: 'full-bots',
    players: '5-10',
    summary: '圆桌骑士与爪牙暗中角力。组队出征、任务成败、刺客猎杀梅林——信任是最稀缺的资源。',
    encyclopedia: `阿瓦隆（The Resistance: Avalon）强调隐藏身份与任务投票。好人阵营需完成足够成功任务；奸徒可在任务中出失败票。刺客可在好人胜利时刺杀梅林翻盘。
本站实现角色分配、任务组队、投票、任务卡与刺杀阶段，支持 bots 与联机。`,
    tutorial: ['确认隐蔽身份', '队长提名任务小队', '全员投票通过/反对', '任务成员暗票成功/失败', '刺客可刺杀梅林'],
  },
  {
    id: 'chess',
    nameZh: '国际象棋',
    nameEn: 'Chess',
    genre: '古典棋类',
    playable: 'full-ai',
    players: '2',
    summary: '64 格星阵上的王权博弈。从开局理论到残局残光，每一步都是时空折叠。',
    encyclopedia: `国际象棋是全球通用的抽象战略游戏。王、后、车、象、马、兵各具独特走法。目标将死对方国王。本引擎支持易位、吃过路兵、升变，并配备合法着法高亮与启发式 AI。`,
    tutorial: ['点击棋子查看合法格', '注意易位与升变', 'AI 教练提供启发式评分建议'],
  },
  {
    id: 'checkers',
    nameZh: '跳棋',
    nameEn: 'Chinese Checkers',
    genre: '竞速棋类',
    playable: 'full-ai',
    players: '2-6',
    summary: '六角星盘上的跃迁竞赛。单步或连续跳跃，率先占满对角营地者胜。',
    encyclopedia: `跳棋（中国跳棋）使用六角星棋盘。棋子可移入相邻空点，或跳跃相邻棋子（可连续跳）。目标是将己方所有棋子移入对面营地。本站实现 2 人对战 AI。`,
    tutorial: ['选择棋子后高亮可落点', '跳跃可连续进行', '先占满对方营地获胜'],
  },
  {
    id: 'mahjong',
    nameZh: '麻将',
    nameEn: 'Mahjong',
    genre: '牌类',
    playable: 'full-bots',
    players: '4',
    summary: '万饼条字的量子纠缠。吃碰杠胡，听牌一线之间，四家博弈于霓虹牌桌。',
    encyclopedia: `简化麻将：标准万/饼/条 + 字牌。支持吃、碰、杠、胡，三家机器人。以基本型和牌（4 面子 + 1 将）判定。适合快速体验牌感与牌理。`,
    tutorial: ['摸打循环', '可吃下家打出的顺子牌', '可碰/杠任意家', '和牌宣告胡'],
  },
  {
    id: 'gomoku',
    nameZh: '五子棋',
    nameEn: 'Gomoku',
    genre: '古典棋类',
    playable: 'full-ai',
    players: '2',
    summary: '黑白落子如星轨连珠。五子一线即胜，攻防瞬息万变。',
    encyclopedia: `五子棋在 15×15 棋盘上轮流落子，先连成五子者胜。本引擎含威胁评估 AI 与合法落点提示，适合热身与战术训练。`,
    tutorial: ['黑先白后轮流落子', '横竖斜连五即胜', 'AI 会优先阻断你的四连'],
  },
  {
    id: 'go',
    nameZh: '围棋',
    nameEn: 'Go',
    genre: '古典棋类',
    playable: 'encyclopedia',
    players: '2',
    summary: '黑白天地，气与眼的终极哲学。围地收官，宇宙级的简洁。',
    encyclopedia: `围棋是最古老的抽象策略游戏之一。棋子在交叉点落子，气尽被提。以围地多少定胜负。完整引擎将在后续星域版本上线，当前提供图鉴与 Coming Soon 房间。`,
    tutorial: ['即将开放完整对局', '可先浏览图鉴了解气与眼'],
  },
  {
    id: 'junqi',
    nameZh: '军棋',
    nameEn: 'Jungle / Land Battle Chess',
    genre: '军略棋类',
    playable: 'encyclopedia',
    players: '2',
    summary: '暗棋军阶对决，工兵挖雷，司令镇场。布局即命运。',
    encyclopedia: `军棋（陆战棋）双方暗子布局，按军阶比大小，遇地雷与炸弹有特殊规则。目标挖掉对方军旗。完整可玩版本筹备中。`,
    tutorial: ['Coming Soon'],
  },
  {
    id: 'doudizhu',
    nameZh: '斗地主',
    nameEn: 'Dou Dizhu',
    genre: '牌类',
    playable: 'encyclopedia',
    players: '3',
    summary: '一打二的经典牌局。叫分抢庄，炸弹王炸撕裂星空。',
    encyclopedia: `斗地主是三人牌类：地主对阵两名农民。按牌型出牌，先出完手牌者胜。完整房间即将开放。`,
    tutorial: ['Coming Soon'],
  },
  {
    id: 'uno',
    nameZh: 'UNO',
    nameEn: 'UNO',
    genre: '牌类',
    playable: 'encyclopedia',
    players: '2-8',
    summary: '色彩与功能牌的连锁反应。+4 与跳过在星舰休息室掀起风暴。',
    encyclopedia: `UNO 通过颜色/数字匹配出牌，功能牌改变流向或惩罚对手。先出完者胜。联机房间筹备中。`,
    tutorial: ['Coming Soon'],
  },
  {
    id: 'holdem',
    nameZh: '德州扑克',
    nameEn: "Texas Hold'em",
    genre: '牌类',
    playable: 'encyclopedia',
    players: '2-9',
    summary: '底牌与公共牌构筑成牌。筹码即勇气，诈唬是艺术。',
    encyclopedia: `德州扑克每位玩家两张底牌，五张公共牌分轮发出。通过下注轮争夺底池。完整牌局引擎即将上线。`,
    tutorial: ['Coming Soon'],
  },
  {
    id: 'monopoly',
    nameZh: '大富翁',
    nameEn: 'Monopoly-like',
    genre: '经济桌游',
    playable: 'encyclopedia',
    players: '2-6',
    summary: '地产、租金与机遇卡。在环形星港地图上积累星际资本。',
    encyclopedia: `大富翁类游戏围绕掷骰、购地、收租与机遇事件。完整经济模拟房间即将开放。`,
    tutorial: ['Coming Soon'],
  },
];

export function getGame(id: string) {
  return GAMES.find((g) => g.id === id);
}
